### PR TITLE
Fixed question mark

### PR DESCRIPTION
**Pull request by jnm2**
No urgency for a release, just thought I'd fix it.

### CODE REVIEW

**Comment by trailmax** [comment]
A question mark? yet broke the build! -)))

**Comment by trailmax** [comment]
Good stuff. Never noticed it there! Thanks!

**Comment by jnm2** [comment]
> A question mark? yet broke the build! -)))

Haha, I'm sorry!

**Comment by trailmax** [comment]
No worries, it is a stupid test, should assert on something better than full exception message

**Comment by jnm2** [comment]
Well the more I think about it the smarter that test sounds.

**Pull request merged**
